
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1203629
	#The name of the modpack
	modpackName = "Beyond Ascension"
	#The version of the modpack
	modpackVersion = "Ver1.9.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

