
["Boss Health"]
	#Health for specified mob.
	"Gob, King of Gnomes Health" = 550.0
	#Health for specified mob.
	"Super Sniffer Health" = 850.0
	#Health for specified mob.
	"Ultra Sniffer Health" = 1200.0
	#Health for specified mob.
	"Trial Guardian Health" = 900.0
	#Health for specified mob.
	"Virtue Health" = 800.0
	#Health for specified mob.
	"Enchanter Merlin Health" = 900.0
	#Health for specified mob.
	"Sorceress Circe Health" = 900.0
	#Health for specified mob.
	"Archmage Gundalf Health" = 1150.0
	#Health for specified mob.
	"Multiplayer Boss Health Scaling" = true

["Mob Health"]
	#Health for specified mob.
	"Duskrok Health" = 100.0
	#Health for specified mob.
	"Hellrok Health" = 200.0

[Bosses]
	#If true, Terramity bosses will despawn after you die.
	"Can Bosses Despawn" = true

["Mob Griefing"]
	#If false, Terramity mobs will (mostly) not damage terrain.
	MobGriefing = true

